name: plantguardian
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  saver_gallery: ^4.0.1
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
